version: '3.7'

services:
  minecraft:
    image: felixklauke/paperspigot:1.16.3
    container_name: minecraft
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 4096M
    restart: always
    networks:
      - default
      - minecraft
    ports:
      - 25565:25565
    environment:
      - JAVA_HEAP_SIZE=3584M
    volumes:
      - /opt/data/minecraft/config:/opt/minecraft/config
      - /opt/data/minecraft/worlds:/opt/minecraft/worlds
      - /opt/data/minecraft/plugins:/opt/minecraft/plugins
      - /opt/data/minecraft/data:/opt/minecraft/data
      - /opt/data/minecraft/logs:/opt/minecraft/logs
      - /opt/data/minecraft/server-icon.png:/opt/minecraft/server/server-icon.png

networks:
  minecraft:
    external: true
